*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 10.06.2009 at 18:40:13 by user D00211
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZDIMENSION01TOP.                  " Global Data
  INCLUDE LZDIMENSION01UXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZDIMENSION01F00                        . " subprograms
  INCLUDE LZDIMENSION01I00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZDIMENSION01F...                  " Subprograms
* INCLUDE LZDIMENSION01O...                  " PBO-Modules
* INCLUDE LZDIMENSION01I...                  " PAI-Modules

INCLUDE LZDIMENSION01F01.
